from __future__ import annotations

from .capability_packs import Capability, CapabilityCandidate


def _candidate(
    provider: str,
    ref: str,
    *,
    priority: int = 10,
    defaults: dict[str, object] | None = None,
    note: str = "",
) -> CapabilityCandidate:
    return CapabilityCandidate(
        provider=provider,
        ref=ref,
        priority=priority,
        defaults=defaults or {},
        note=note,
    )


def build_extra_gaming_capabilities() -> list[Capability]:
    return [
        Capability(
            id="steam.player.resolve",
            name="Steam vanity/IGN lookup",
            description="Resolve a public Steam vanity profile name to SteamID64.",
            pack="steam",
            tags=("gaming", "steam", "ign", "vanity", "steamid", "lookup"),
            candidates=(_candidate("steam", "steam:resolve-vanity"),),
        ),
        Capability(
            id="steam.player.profile",
            name="Steam public player profile",
            description="Retrieve public Steam persona/profile summaries for SteamID64 values.",
            pack="steam",
            tags=("gaming", "steam", "player", "profile", "persona"),
            candidates=(_candidate("steam", "steam:player-summaries"),),
        ),
        Capability(
            id="steam.games.recent",
            name="Steam recently played games",
            description="Retrieve recent public game/playtime information for a Steam profile.",
            pack="steam",
            tags=("gaming", "steam", "games", "recent", "playtime"),
            candidates=(_candidate("steam", "steam:recent-games"),),
        ),
        Capability(
            id="steam.games.owned",
            name="Steam public game library",
            description="Retrieve public owned-game/playtime data when the player's game details are visible.",
            pack="steam",
            tags=("gaming", "steam", "games", "library", "playtime"),
            candidates=(_candidate("steam", "steam:owned-games"),),
        ),
        Capability(
            id="steam.player.level",
            name="Steam player level",
            description="Retrieve the public Steam account level for a SteamID64.",
            pack="steam",
            tags=("gaming", "steam", "player", "level", "profile"),
            candidates=(_candidate("steam", "steam:player-level"),),
        ),
        Capability(
            id="steam.player.badges",
            name="Steam public badges and XP",
            description="Retrieve public Steam badges and XP metadata for a SteamID64.",
            pack="steam",
            tags=("gaming", "steam", "badges", "xp", "profile"),
            candidates=(_candidate("steam", "steam:badges"),),
        ),
        Capability(
            id="steam.game.achievements",
            name="Steam per-game achievements",
            description="Retrieve public achievement state for any Steam AppID that exposes player achievements.",
            pack="steam",
            tags=("gaming", "steam", "game", "achievements", "stats"),
            candidates=(_candidate("steam", "steam:player-achievements"),),
        ),
        Capability(
            id="steam.game.stats",
            name="Steam per-game player stats",
            description="Retrieve public per-game Steamworks stats for any AppID that exposes user stats.",
            pack="steam",
            tags=("gaming", "steam", "game", "stats", "performance"),
            candidates=(_candidate("steam", "steam:user-stats"),),
        ),
        Capability(
            id="steam.game.schema",
            name="Steam game stats and achievement schema",
            description="Inspect the published Steamworks stat/achievement schema for a Steam AppID.",
            pack="steam",
            tags=("gaming", "steam", "game", "schema", "stats", "achievements"),
            candidates=(_candidate("steam", "steam:game-schema"),),
        ),
        Capability(
            id="steam.game.global_achievements",
            name="Steam global achievement percentages",
            description="Retrieve global achievement unlock rates for a Steam AppID.",
            pack="steam",
            tags=("gaming", "steam", "game", "achievements", "global", "stats"),
            candidates=(_candidate("steam", "steam:global-achievements"),),
        ),
        Capability(
            id="steam.game.current_players",
            name="Steam current player count",
            description="Retrieve the current player count for a Steam AppID.",
            pack="steam",
            tags=("gaming", "steam", "game", "players", "online", "activity"),
            candidates=(_candidate("steam", "steam:current-players"),),
        ),
        Capability(
            id="steam.games.catalog",
            name="Steam app catalog discovery",
            description="Browse bounded pages of the Steam app catalog to resolve titles and AppIDs.",
            pack="steam",
            tags=("gaming", "steam", "games", "catalog", "appid", "discovery"),
            candidates=(_candidate("steam", "steam:app-catalog"),),
        ),
        Capability(
            id="minecraft.player.identity",
            name="Minecraft public identity lookup",
            description="Resolve a Minecraft username or UUID through the cross-platform PlayerDB identity layer.",
            pack="minecraft",
            tags=("gaming", "minecraft", "identity", "ign", "uuid"),
            candidates=(_candidate("playerdb", "playerdb:minecraft"),),
        ),
        Capability(
            id="steam.player.identity",
            name="Steam public identity normalization",
            description="Normalize a supported public Steam identifier through PlayerDB.",
            pack="steam",
            tags=("gaming", "steam", "identity", "steamid", "lookup"),
            candidates=(_candidate("playerdb", "playerdb:steam"),),
        ),
        Capability(
            id="xbox.player.identity",
            name="Xbox public identity lookup",
            description="Resolve a public Xbox gamertag or supported identifier through PlayerDB.",
            pack="xbox",
            tags=("gaming", "xbox", "identity", "gamertag", "lookup"),
            candidates=(_candidate("playerdb", "playerdb:xbox"),),
        ),
        Capability(
            id="hytale.player.identity",
            name="Hytale public identity lookup",
            description="Resolve a public Hytale player identifier through PlayerDB where available.",
            pack="hytale",
            tags=("gaming", "hytale", "identity", "ign", "lookup"),
            candidates=(_candidate("playerdb", "playerdb:hytale"),),
        ),
        Capability(
            id="riot.account.lookup",
            name="Riot ID lookup",
            description="Resolve a Riot ID to PUUID using Riot's official ACCOUNT-V1 API.",
            pack="riot",
            tags=("gaming", "riot", "riot-id", "ign", "puuid", "lookup"),
            candidates=(_candidate("riot", "riot:account-by-riot-id"),),
        ),
        Capability(
            id="riot.account.reverse",
            name="Riot PUUID to Riot ID",
            description="Resolve a PUUID to current Riot ID account information.",
            pack="riot",
            tags=("gaming", "riot", "puuid", "riot-id", "lookup"),
            candidates=(_candidate("riot", "riot:account-by-puuid"),),
        ),
        Capability(
            id="league.player.profile",
            name="League player profile",
            description="Retrieve League summoner/profile metadata by PUUID from Riot's official API.",
            pack="league",
            tags=("gaming", "league", "lol", "player", "profile"),
            candidates=(_candidate("riot", "riot:lol-summoner-by-puuid"),),
        ),
        Capability(
            id="league.rank.current",
            name="League current ranked entries",
            description="Retrieve current League ranked queues, tiers, divisions and LP by PUUID.",
            pack="league",
            tags=("gaming", "league", "lol", "rank", "tier", "lp"),
            candidates=(_candidate("riot", "riot:lol-ranked-entries"),),
        ),
        Capability(
            id="league.champion.mastery",
            name="League champion mastery and mains",
            description="Retrieve champion mastery rows for a PUUID to identify mains/top mastered champions.",
            pack="league",
            tags=("gaming", "league", "lol", "champions", "mastery", "mains", "most-used"),
            candidates=(_candidate("riot", "riot:lol-champion-mastery"),),
        ),
        Capability(
            id="league.matches.recent",
            name="League recent match IDs",
            description="Retrieve recent League Match-V5 IDs for a PUUID.",
            pack="league",
            tags=("gaming", "league", "lol", "matches", "recent", "history"),
            candidates=(_candidate("riot", "riot:lol-match-ids", defaults={"count": 20}),),
        ),
        Capability(
            id="league.match.detail",
            name="League match detail",
            description="Retrieve one official League Match-V5 match payload by match ID.",
            pack="league",
            tags=("gaming", "league", "lol", "match", "stats"),
            candidates=(_candidate("riot", "riot:lol-match"),),
        ),
        Capability(
            id="tft.matches.recent",
            name="TFT recent match IDs",
            description="Retrieve recent Teamfight Tactics match IDs for a PUUID from Riot's official API.",
            pack="tft",
            tags=("gaming", "tft", "teamfight-tactics", "matches", "recent"),
            candidates=(_candidate("riot", "riot:tft-match-ids", defaults={"count": 20}),),
        ),
        Capability(
            id="tft.match.detail",
            name="TFT match detail",
            description="Retrieve one official Teamfight Tactics match payload by match ID.",
            pack="tft",
            tags=("gaming", "tft", "teamfight-tactics", "match", "placement", "units"),
            candidates=(_candidate("riot", "riot:tft-match"),),
        ),
    ]
